# Generated by Django 4.2.6 on 2023-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("salary", models.IntegerField()),
            ],
            options={
                "ordering": ["date_of_birth"],
                "abstract": False,
            },
        ),
    ]
