# Generated by Django 4.2.6 on 2023-10-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_clerks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clerks",
            options={},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={},
        ),
    ]
